import AnimatedText from '@/components/AnimatedText'
import TransitionEffect from '@/components/TransitionEffect'
import React from "react";
import { motion } from "framer-motion";
import Head from 'next/head'
import Layout from '@/components/Layout';
import Team from '@/components/Team';

import suraj from "../../public/images/team/suraj.png"
import ck from '../../public/images/ck.png'
import ParticleContainer from '@/components/ParticleContainer';
import Image from 'next/image';
import team from "../../public/images/backgrounds/team.jpeg"



const projectTeam = [
  {
    name: "Nitin Aravind Birur",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Kavya Agarwal",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  }, {
    name: "Akshay Shukla",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Himanshu",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Shubhang Gautam",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Granth Jain",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Sriram Hebbale",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Saksham Bansal",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Jay Agarwal",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Archit Jain",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Harshit Saraf",
    role: "Project Team",
    linkedIn: "/",
    link: "/",
    image: ck
  }
]

const researchTeam = [
  {
    name: "Aryan Bakshi",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Utkarsh Tiwari",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  }, {
    name: "Aviral Gupta",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Rachit Gandi",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Saurabh Bhandari",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Ameesh Sethi",
    role: "Research Team",
    linkedIn: "/",
    link: "/",
    image: ck
  }
]

const webTeam = [
  {
    name: "Suraj Pal",
    role: "WebDev Lead",
    linkedIn: "https://www.linkedin.com/in/surajpverma/",
    link: "https://github.com/Surajpverma",
    image: suraj
  }
]

const psdTeam = [
  {
    name: "Shivika Dhandhania",
    role: "PSD Team",
    linkedIn: "/",
    link: "/",
    image: ck
  }
]

const facultyTeam = [
  {
    name: "Dr. Kamlesh Tiwari",
    role: "Faculty Mentor",
    linkedIn: "/",
    link: "/",
    image: ck
  },
  {
    name: "Dr. Kamlesh Tiwari",
    role: "Ashutosh Bhatia",
    linkedIn: "/",
    link: "/",
    image: ck
  }
]

const contact = () => {
  return (
    <>
      <Head>
        <title>KXR | Team</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />
      <ParticleContainer />
      <div className='w-screen h-screen -z-50 fixed overflow-hidden'>
        <Image src={team} className='object-cover h-full w-full'/>
      </div>

      <main className='flex w-full flex-col items-center justify-center'>
        <Layout className='pt-32'>


          <AnimatedText text="Visionaries in Unity!" className='my-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8 ' />
          <p className='text-2xl md:text-xl font-medium mb-16 text-center'> Embark on an awe-inspiring voyage through the veil of reality with our team of tech sorcerers and art visionaries, where imagination and innovation converge to craft immersive worlds beyond imagination. 🚀🎨🌌 </p>

          <AnimatedText text="Faculty Mentors" className='my-16 !text-6xl sm:!text-4xl xs:!text-4xl sm:mb-8 ' />
          <div className='flex items-center justify-center gap-6' >

            {
              facultyTeam.map((member) => {
                return (
                  <Team name={member.name} role={member.role} linkedIn={member.linkedIn} link={member.link} image={member.image} key={member.name} />
                )
              })
            }

          </div>

          <AnimatedText text="Project Team" className='my-16 !text-6xl sm:!text-4xl xs:!text-4xl sm:mb-8 ' />
          <div className='grid grid-cols-5 items-center gap-4 gap-y-10 justify-center md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4' >

            {
              projectTeam.map((member) => {
                return (
                  <Team name={member.name} role={member.role} linkedIn={member.linkedIn} link={member.link} image={member.image} key={member.name} />
                )
              })
            }

          </div>

          <AnimatedText text="Research Team" className='my-16 !text-6xl sm:!text-4xl xs:!text-4xl sm:mb-8 ' />
          <div className='grid grid-cols-5 items-center gap-4 gap-y-10 justify-center md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4' >

            {
              researchTeam.map((member) => {
                return (
                  <Team name={member.name} role={member.role} linkedIn={member.linkedIn} link={member.link} image={member.image} key={member.name} />
                )
              })
            }
          </div>

          <AnimatedText text="WebDev Team" className='my-16 !text-6xl sm:!text-4xl xs:!text-4xl sm:mb-8 ' />
          <div className='flex items-center justify-center' >

            {
              webTeam.map((member) => {
                return (
                  <Team name={member.name} role={member.role} linkedIn={member.linkedIn} link={member.link} image={member.image} key={member.name} />
                )
              })
            }

          </div>

          <AnimatedText text="PSD Team" className='my-16 !text-6xl sm:!text-4xl xs:!text-4xl sm:mb-8 ' />
          <div className='flex items-center justify-center' >

            {
              psdTeam.map((member) => {
                return (
                  <Team name={member.name} role={member.role} linkedIn={member.linkedIn} link={member.link} image={member.image} key={member.name} />
                )
              })
            }

          </div>


        </Layout>
      </main>
    </>
  )
}

export default contact
