import AnimatedText from '@/components/AnimatedText'
import TransitionEffect from '@/components/TransitionEffect'
import React, { useState } from "react";
import { motion } from "framer-motion";
import Head from 'next/head'




import Members from '@/components/Members';

const contact = () => {
  return (
    <div className='glassbg z-10'>
      <Head>
        <title>SPV || contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <Members />
      
    </div>
  )
}

export default contact
